# Eccentrist theme for Hugo

name = "Eccentrist"
license = "MIT"
licenselink = "https://github.com/MrGlitchByte/eccentrist/blob/master/LICENSE"
description = "A powerful, lightweight Tuffte CSS theme for Hugo built with Tailwind CSS."

homepage = "https://github.com/MrGlitchByte/eccentrist/"
demosite = "https://MrGlitchByte.github.io/Eccentrist/"

tags = ["blog", "minimal", "responsive", "dark mode", "dark", "light", "tailwind", "personal"]
features = ["syntax higlighting", "dark mode", "emoji"]

[author]
  name = "Mr Glitchbyte"
  homepage = "https://glitchbyte.io"
