theme = "tome"
languageCode = "en-us"
baseurl = "http://example.com/"
title = "Hugo Tailwindcss Starter"

author = "Mr. Glitchbyte"
copyright = "Copyright © 2021, Mr. Glitchbyte, all rights reserved."

[params]
    name = "Hugo Tailwindcss Starter"
    description = "A simple bootstraped theme for Hugo, build with Tailwindcss."

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
